# ##########################################################
# +------------------------------------------------------+ #
# |                      WARNING                         | #
# +------------------------------------------------------+ #
# ##########################################################
# All data stored in items is encrypted with RC5. 
# CHANGING THE RC5 KEY WILL INVALIDATE ALL BACKPACKS!
# Just in case, keep a backup of the key!

backpacks:
  example:
    item: Leather
    item-name: "&rSmall Satchel"
    lore:
    - "&c9 Slot Satchel"
    recipe:
      shaped: true
      ingredients:
        L: Leather
        W: Wool
      matrix:
      - LLL
      - LWL
      - LLL
    rows: 1
    title: "Small Satchel"
    check-permission: false

cache-clear-interval: 1800

RC5:
  key: ''

messages:
  noPermission: '&cYou do not have permission to do that!'