# ##########################################################
# +------------------------------------------------------+ #
# |                      WARNING                         | #
# +------------------------------------------------------+ #
# ##########################################################
# All data stored in items is encrypted with RC5. 
# CHANGING THE RC5 KEY WILL INVALIDATE ALL BACKPACKS!
# Just in case, keep a backup of the key!

backpacks:
  small:
    item: Leather
    itemName: &rSmall Satchel
    lore:
    - 9 Slot Satchel
    recipe:
      shaped: true
      ingredients:
        L: Leather
        W: Wool
      matrix:
      - LLL
      - LWL
      - LLL
    rows: 3
    title: Small Satchel
    canContainOther: false

cacheClearInterval: 3600

rc5:
  key: ''

messages:
  noPermission: '&cYou do not have permission to do that!'